### ISSUE TITLE
Resolve dependencys of webpack and angular (ordering)

### ISSUE THREAD

**Issue by floisloading** [yunity/yunity-webapp#15]
Temp Hack: in index.html the angular script is loaded

**Comment by nicksellen** [comment]
I think something like https://github.com/stackfull/angular-webpack-plugin/issues/9#issuecomment-50125250 might do the trick (expose and/or export webpack loaders)

**Comment by ghost** [comment]
when setting up the dev environment as per yunity/yunity-webapp/README.md, I had to install webpack-dev-server as well, something to add to instructions later

**Comment by ghost** [comment]
Changing the way angular is imported to the ES6 standard fixed the issue.
i.e. using `import angular from 'angular';`, 
rather than
`require('angular');`
or
`var angular = require('angular');`

Additionally, `angular` needs to be imported before `yunityAPI` - there seems to be an issue with how babel+webpack orders the dependencies
